config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index'

  get "session", to:"artists#sign_in"
  post "session", to:"artists#session_up"
  delete "session", to:"artists#session_down"

  get "arts", to: "arts#index"

  resources :artists, except:[:destroy] do
  	resources :arts ,except:[:destroy]
  end

  resources :categories, except:[:new,:create,:update,:edit,:destroy]
  resources :category_groups, except:[:new,:create,:update,:edit,:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
	belongs_to :artist
	has_and_belongs_to_many :categories

	has_attached_file :picture, styles: { medium: "250x250>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :arts

  	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	validates :name, presence: true, length: 3..32 , uniqueness: true
	validates :password, presence: true, length: 6..32
	validates :email, presence: true, length: 3..32, uniqueness: true
	validates :phone, presence: true, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
	belongs_to :category_group
	has_and_belongs_to_many :arts
end

app/models/category_group.rb
class CategoryGroup < ApplicationRecord
	has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery with: :exception
  	before_action :get_current_artist,except:[:aut_artist!]

  	private 

  	def get_current_artist
  		if(session[:current_artist_id])
  			@current_artist=@current_artist=Artist.find(session[:current_artist_id])
  		end
  	end

	def aut_artist!
		if(!session[:current_artist_id])
			redirect_to session_path
		else
			get_current_artist
		end
	end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	before_action :get_artist, only:[:show,:edit,:update,:destory]
	#before_action :aut_artist!, except:[:session_up,:sign_in]

	def index
		@artists=Artist.all
	end

	def show
		@arts = Art.where(artist_id: @artist.id)
	end

	def sign_in
		@navbar_off = true
		if(@current_artist)
			redirect_to artist_path(@current_artist.name) 
		end
		#@artist=Artist.new
	end

	def session_up
		if(!@current_artist)
			@current_artist=Artist.find_by(email: params[:artist][:email],password: params[:artist][:password])
			if(@current_artist)
				session[:current_artist_id]= @current_artist.id
				redirect_to artist_path(@current_artist.name)  	
			else
				render 'sign_in'
			end
		else
			redirect_to artist_path(@current_artist.name)
		end
	end

	def session_down
		reset_session
		@current_artist = nil
		redirect_back fallback_location: root_path
	end

	def new
		@navbar_off = true
	end

	def create
		@artist=Artist.create(artist_params)
  		if @artist.save
			redirect_to artist_path(@artist.name)  		
    	else
  			render 'new'
  		end
	end

	def edit
		
	end

	def update
    	if @artist.id == @current_artist.id
  			#Tag.new.all_tags_c(@art,params[:art][:all_tags])
  			@artist.update(artist_params)
    	end
  		redirect_to artist_path(@artist.name)
	end

	private 

	def get_artist
		@artist = Artist.find_by(name: params[:id])
		if(!@artist)
			@artist=Artist.find_by(id: params[:id])
		end
	end

	def artist_params
		params.require(:artist).permit(:name,:password,:description,:phone,:email,:avatar)
	end

end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
	before_action :aut_artist!, except:[:show,:index]
	before_action :get_art,except:[:index,:new,:create]
	before_action :get_artist, except:[:index]
  before_action :get_groups, only:[:new,:edit]

	def index
    #@categories=Category.all

    if(Artist.find_by(name: params[:artist_id])|| Artist.find_by(id: params[:artist_id]))
      @artist = Artist.find_by(name: params[:artist_id])
      @artist ||=Artist.find(params[:artist_id])
      @arts=Art.where(artist_id: @artist.id)
    else
      #Фільтр за категоріями  при наявності категорій для фільтрування вибирає тільки їх спільні випадки 
      #По можливості зробити фільтр , щоб у випаду відсутності варіантів по вибраним категоріям знаходив ймовірні комбінаціїї які підпадають під задані параметри пошуку. ТОбто не загальна сума а сума відносна , випадки без однієїї або без декількох
      if(!@categories)
        @arts=Art.all
      else
        @arts = Art.ids
        @categories.each{|category|
          @arts = @arts & category.arts.ids
        }
        if(!@arts)
          @arts = []
        else
          @arts.map{|art|
            pp art=art.to_s
          }
          @arts = Art.find(@arts)
        end
      end
    end
  end

  def show
  
  end

	def new
    @navbar_off = true	
  end

  def create
    #pp params[:categories_ids]
  	params[:art][:artist_id]=@current_artist.id
    @categories = Category.find(params[:categories_ids])
  	@art=Art.create(art_params)
    @art.categories = @categories
  	if @art.save
		redirect_to artist_art_path(@artist.name,@art.id)  		
    else
  		render 'new'
  	end
  end

  def edit
	 @navbar_off = true	  		
  end

  def update
    if @art.artist.id == @current_artist.id
      @categories = Category.find(params[:categories_ids])
      @art.categories.clear
      @art.categories = @categories
  		@art.update(art_params)
    end
  	redirect_to artist_art_path(@artist.name,@art.id)
  end

  def destroy
    if @art.artist.name == @current_artist.name
  		@art.destroy
    end
  	redirect_to artist_path(@current_artist.name)
  end

  private 

  def get_artist
		@artist = Artist.find_by(name: params[:artist_id])
		@artist ||=Artist.find(params[:artist_id])
	end

  def get_art
  	@art = Art.find(params[:id])
  end

  def art_params
  	params.require(:art).permit(:name,:description,:artist_id,:price,:picture)
  end

  def get_groups
    @groups = CategoryGroup.all
    @categories = []
    @groups.each{|group|
      @categories[group.id] = Category.where(category_group_id: group.id)
      }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categoris = Category.all
	end

	def show
		@category = Category.find_by(name: params[:id])
		@category ||=Category.find_by(id: params[:id])
		@arts = @category.arts
	end

end

app/controllers/category_groups_controller.rb
class CategoryGroupsController < ApplicationController

	def index
		@groups = CategoryGroup.all
		@categories = []
		@groups.each{|group|
			@categories[group.id] = Category.where(category_group_id: group.id)
			}
	end

	def show
		@group = CategoryGroup.find_by(name: params[:id])
		@group ||=CategoryGroup.find_by(id: params[:id])
		@categories = Category.where(category_group_id: @group.id)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	#before_action :aut_artist! 

  	def index
  		@navbar_off = true
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_groups_helper.rb
module CategoryGroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/artists/_artist.html.erb
<h2><%=link_to artist.name , artist_path(artist.name)%></h2>
<h3><%= artist.description %></h3>

app/views/artists/_artist_list.html.erb
<h4><%=link_to artist.name , artist_path(artist.name)%></h4>

app/views/artists/_form.html.erb
<div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control',autofocus: true %>
</div>

<div class="form-group">
	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>
</div>
	 
<div class="form-group">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>
</div> 

<div class="custom-file">
    <%=f.label :avatar, class:"custom-file-label" %>
	<%= f.file_field :avatar, class:"custom-file-input", id:"customFile" %>
</div>

<div class="form-group">
	<%= f.label :description %>
	<%= f.text_area :description, class: 'form-control'%>
</div>

<div class="form-group">
	<%= f.label :email %>
	<%= f.text_area :email, class: 'form-control'%>
</div>

<div class="form-group">
	<%= f.label :phone %>
	<%= f.text_area :phone, class: 'form-control'%>
</div>

<%= f.submit :commit %>

app/views/artists/edit.html.erb
<%= form_for @artist, url: artist_path(@artist.name), method: :patch do  |f| %>
	<%= render  "artists/form", f:f%>
<%end%>

app/views/artists/index.html.erb
<div class="row">
<% @artists.each do |artist| %>
<div class="col-md-6 .col-xs-6">
<figure class="fir-image-figure">
	<%=link_to artist_path(artist.name), class: "fir-imageover" do%>
	<%=image_tag artist.avatar(:thumb),class: "fir-author-image fir-clickcircle" %>
	<%end%>
	<figcaption>
  <div class="fig-author-figure-title"><h3><%=link_to artist.name , artist_path(artist.name)%></h3></div>
  <div class="fig-author-figure-title">tel: <%= artist.phone%></div>
  <div class="fig-author-figure-title">email: <%= artist.email%></div>
 </figcaption>
</figure>
</div>
<%end%>

app/views/artists/new.html.erb
<%= form_for :artist, url: artists_path do |f| %>
	<%= render  "artists/form", f:f%>
<%end%>

app/views/artists/show.html.erb
<div class="row content">
<h1><%=@artist.name%></h1>
<h3>Список картин:</h3>
<% if @arts%>
	<%=render @arts%>
<%else%>
	Ще не опублікував роботи
<%end%>
</div>

app/views/artists/sign_in.html.erb
<div class="row content">	
	<%=form_for :artist, url: session_path do |f|%>
		<div class="form-group">
			<%= f.label :email %>
			<%= f.text_field :email, class: 'form-control',autofocus: true %>
		</div>

		<div class="form-group">
			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>
		</div>
	 
		<!-- <div class="form-group">
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>
		</div> -->
		
		<%= f.submit :commit %>
	<%end%>
</div>	

app/views/arts/_art.html.erb
<div class="col-md-4 .col-xs-12">
<div class="card">
	<%=image_tag art.picture.url(:medium),width:250, height:250  %>
  	<div class="container">
		<h3><%=link_to art.name, artist_art_path(art.artist.name,art.artist.id)%></h3> 
		<% art.categories.each do |category|%>
			<%=link_to category.name, category_path(category.name), class: 'badge badge-secondary' %> 
		<%end%>
  	</div>
</div>
</div>

app/views/arts/_form.html.erb
<div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control',autofocus: true %>
</div>

<div class="custom-file">
	<%= f.file_field :picture, class:"custom-file-input", id:"customFile" %>
    <%=f.label :picture, class:"custom-file-label" %>
</div>

<div class="form-group">
	<%= f.label :description %>
	<%= f.text_area :description, class: 'form-control'%>
</div>

<div class="form-group">
	<%= f.label :price %>
	<%= f.text_field :price, class: 'form-control' %>
</div>

	<div class="form-group">
	<%= f.label :artist_name %>:
	<%= f.label @current_artist.name, class: 'form-control'%>
</div>

<div>
	<% @groups.each do |group| %>
		<p><%=group.name%>:</p>
		<% @categories[group.id].each do |category|%>
			<%=check_box_tag('categories_ids[]',category.id)%>
			<%=category.name%>
		<%end%>
		<hr>
	<%end%>
</div>

<%= f.submit :commit %>

app/views/arts/edit.html.erb
<%=form_for :art, url:artist_art_path(@artist.name), method: :patch do |f|%>
	<%= render '/arts/form', f:f%>
<%end%>

app/views/arts/index.html.erb
<div class="row content">
<%=render @arts%>
</div>

app/views/arts/new.html.erb
<%=form_for :art, url:artist_arts_path(@artist.name) do |f|%>
	<%= render '/arts/form', f:f%>
<%end%>

app/views/arts/show.html.erb
<div class="row content">
<h1><%=@art.name%></h1>
<%=image_tag @art.picture.url ,width:100%>
<p><%=@art.description%></p>
</div>

app/views/categories/_category.html.erb
<h5><%=link_to category.name, category_path(category.name) %></h5>

app/views/categories/index.html.erb
<%=render @categories %> 

app/views/categories/show.html.erb
<h1>Категорія - <%=@category.name %></h1>
<h3>Перелік картин:</h3>
<%= render @arts%>

app/views/category_groups/_category_group.html.erb
<h1><%=link_to category_group.name , category_group_path(category_group.name) %></h1>
Категорії групи :
<%=render @categories[category_group.id]%>
<hr>

app/views/category_groups/index.html.erb
<%=render @groups %> 

app/views/category_groups/show.html.erb
<h1>Група - <%=@group.name %></h1>
<h3>Перелік категорій</h3>
<%=render @categories %> 

app/views/layouts/_navbar.html.erb
<header class="main">

<div class="row">
  <%=link_to root_path , class:"logo" do%>ArtG<%end%>
  <div class="mobile-toggle">
    <span></span>
    <span></span>
    <span></span>
  </div>

  <div class="navbar-collapse">
    <nav>
      <ul>
        <li><%=link_to "Список художників", artists_path()%></li>
        <li><%=link_to "Список РОБІТ", arts_path()%></li>
        <li>
          <%if @artist %>
            <%=link_to @artist.name, artist_arts_path(@artist.name)%>
          <%else%>
            ХуДОЖНИК НЕ обраний
          <%end%>
        </li>
        <li>
          <%if !@current_artist %>
            <%=link_to "Я художник" , session_path%>
          <%else%>
            <%=@current_artist.name%>
            <%=link_to "Exit", session_path, method: :delete%>
          <%end%>
        </li>
      </ul>
    </nav>
  </div>
</div> <!-- / row -->

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtG</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%if !@navbar_off%>
  		<%=render "layouts/navbar" %>
      <div class="row content">
  	<%end%>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/index.html.erb
<header class="main_h">

<div class="row">
  <%=link_to root_path , class:"logo" do%>ArtG<%end%>
  <div class="mobile-toggle">
    <span></span>
    <span></span>
    <span></span>
  </div>

  <div class="navbar-collapse">
    <nav>
      <ul>
        <li><%=link_to "Список художників", artists_path()%></li>
        <li><%=link_to "Список РОБІТ", arts_path()%></li>
        <li>
          <%if @artist %>
            <%=@artist.name%>
          <%else%>
            ХуДОЖНИК НЕ обраний
          <%end%>
        </li>
        <li>
          <%if !@current_artist %>
            <%=link_to "Я художник" , session_path%>
          <%else%>
            <%=@current_artist.name%>
            <%=link_to "Exit", session_path, method: :delete%>
          <%end%>
        </li>
      </ul>
    </nav>
  </div>
</div> <!-- / row -->

</header>

<div class="hero">

    <h1><span>This is</span><br>Artistic page</h1>

    <div class="mouse">
        <span></span>
    </div>

</div>
<div class="row content">
    <h1 class="sec01">Section 01</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, recusandae, at, labore velit eligendi amet nobis repellat natus sequi sint consectetur excepturi doloribus vero provident consequuntur accusamus quisquam nesciunt cupiditate soluta alias illo et deleniti voluptates facilis repudiandae similique dolore quaerat architecto perspiciatis officiis dolor ullam expedita suscipit neque minima rem praesentium inventore ab officia quos dignissimos esse quam placeat iste porro eius! Minus, aspernatur nesciunt consectetur. Sit, eius, itaque, porro, beatae impedit officia tenetur reiciendis autem vitae a quae ipsam repudiandae odio dolorum quaerat asperiores possimus corporis optio animi quisquam laboriosam nihil quam voluptatum quidem veritatis iste culpa iure modi perspiciatis recusandae ipsa libero officiis aliquam doloremque similique id quasi atque distinctio enim sapiente ratione in quia eum perferendis earum blanditiis. Nobis, architecto, veniam molestias minus iste necessitatibus est ab in earum ratione eveniet soluta molestiae sed illo nostrum nemo debitis. Minus, quod totam aliquam ea asperiores fugit quaerat excepturi dolores ratione numquam consequatur id unde alias provident vero incidunt exercitationem similique consequuntur hic possimus? Fuga, eveniet quaerat inventore corporis laborum eligendi enim soluta obcaecati aliquid veritatis provident amet laudantium est quisquam dolore exercitationem modi? Distinctio, pariatur, ab velit praesentium vitae quidem consequatur deleniti recusandae odit officiis. Quidem, cupiditate.</p>